# DOCKER AS DEPENDENCY
# BUILD TEST VERSION OF REACT PROJECT
# RUN TEST
# BUILD PROD VERSION OF ALL PROJECTS
# PUSH ALL CODE TO GITHUB
# TELL ELASTIC BEANSTALK TO UPDATE

language: generic

sudo: required
servies: -docker

before_install:
  - docker build -t jeremybearimy83/multi-container-test -f ./client/Dockerfile.dev ./client

# PRIMARY TEST RUNNING SECTION IF ANY OF THE SCRIPTS DONT'T RETURN STATUS 0 THEN TESTS WILL FAIL
script:
  - docker run -e CI=true jeremybearimy83/multi-container-test npm test

after_success:
  - docker build -t jeremybearimy83/multi-client ./client
  - docker build -t jeremybearimy83/multi-nginx ./nginx
  - docker build -t jeremybearimy83/multi-worker ./worker
  - docker build -t jeremybearimy83/multi-service ./service

  # TAKE THESE IMAGES AND PUSH THEM TO DOCKER HUB

  # LOG IN TO THE DOCKER CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push jeremybearimy83/multi-client
  - docker push jeremybearimy83/multi-nginx
  - docker push jeremybearimy83/multi-server
  - docker push jeremybearimy83/multi-worker
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-dad-joke"
#   env: "Dockerdadjoke-env"
#   bucket_name: "elasticbeanstalk-us-east-2-430232161444"
#   bucket_path: "docker-dad-joke"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY
